### PR TITLE
Pieskiuw 36 webscraper web view

### PR DESCRIPTION
**Pull request by kamart02**
This PR introduces some major changes in the way that webscrapper works. Due to the multi threaded nature of the code a new requirement was needed to be added.  Celery is an app that allows running multi threaded jobs in Django. This PR also connects the web interface with the webscraping backed and allows to view some basic statistics.
There are some simple changes in the model and webscraper application due to it not functioning properly.

### CODE REVIEW

**Comment by kamart02** [comment]
@MateuszWasilewski  due to introduced changes in webscreaper.py the tests no longer function. I've modified the webscraper such that it will immediately start to add Pets into the database instead of storing them in the memory waiting for pacing. I think that this solution is better due to the fact that we need to wait a long time before creating a next request. What's your opinion?

**Comment by MateuszWasilewski** [comment]
Could you explain here why separate redis instance is required for running separate process?

**Comment by MateuszWasilewski** [comment]
I generally agree with new attempt to store seperate results in db in order not to lose progress but this results in many issues if scraping halts for any reason.
Ex. 
Let's assume that scraper correctly fetches 1/3 of all animals and then some exception happens.
Restarting webscraper will not fetch the rest of animals.

**Comment by MateuszWasilewski** [comment]
Such a big PR / refactor should not be introduced at the sprint end without seperate jira ticket or GH issue.

**Comment by kamart02** [comment]
> Could you explain here why separate redis instance is required for running separate process?

The psycopg-2 application used for communication between Django and the database does has an issue. https://stackoverflow.com/questions/64995178/decryption-failed-or-bad-record-mac-in-multiprocessing is the same error I was getting. There are two ways that i found to bypass this issue. 
1. Use celery and redis
2. Create a new database connection in the thread

The problem with 2. is that we would need to run custom sql queries  instead of using Djangos way of interacting with the database.
Using 1. allows us to easily access the database using the Django style. The difference between this approach and the code already created is only that some parts of the code need to have a special decorator. And when running the specially decorated commands we need to put .delay after them. Most of the work is already done in this PR setting up this new server.

**Comment by kamart02** [comment]
> Furthermore refactoring core functionality ought to update testing for it as well in order to prevent code degradation.

This PR is mostly needed to populate our database with data. The other functionalities of our page remain unchained a do not require use of celery or redis. 



> Such a big PR / refactor should not be introduced at the sprint end without seperate jira ticket or GH issue.

Yes I agree. Just as mentioned above this was needed to populate the databse. I will create a seperate PR that will just create the interface and create new jira task to implement this functionality. As of now the database has some example data so more work can be done with the website.

**Comment by kamart02** [comment]
This PR no longer creates changes for redis and celery. Only creates the web interface. Ready for review.

**Comment by kamart02** [comment]
This PR needs to be merged quickly as it is blocking new tasks.

**Pull request merged**
